name: Run Python Script

#on:
#  schedule:
#    - cron: '*/72 * * * *' # This runs every 72 minutes

jobs:
  build:
    runs-on: alpine-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # Checkout the repository content

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Install the Python version needed

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        env:
          MMO_URL: ${{ secrets.MMO_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py
